version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.8.2

workflows:
  main:
    jobs:
      - build_and_push

jobs:
  build_and_push:
    docker:
      - image: circleci/python:3.8
    environment:
      DOCKER_BUILDKIT: "1"
      AWS_REGION: "ap-northeast-1"
    steps:
      - add_ssh_keys:
          fingerprints:
            - ${SSH_KEY_FINGERPRINT}
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - aws-ecr/build-and-push-image:
          repo: docker_sandbox
          dockerfile: ssh/Dockerfile
          extra-build-args: "--ssh default"
          tag: latest
